### ISSUE TITLE
Egg Identification is Buggy: Allow Unidentified Eggs in Recipes

### ISSUE THREAD

**Issue by jet082** [tinyhoot/SubnauticaRandomiser#42] opened 2022-08-23 19:32 UTC
In my current seed, I have hatched no less than 5 crabsnake eggs, but they are all still ‘unidentified’ and the crabsnakes do not seem to be reproducing, despite being the sole residents of the tank.

As such, unless there’s some mechanic I am missing, this makes the seed impossible, since “Crabsnake Egg” is required for the knife.

It might be best to allow the ‘unidentified’ versions of the eggs in recipes. Unless, again, I’m missing something about the egg mechanics.

**Comment by jet082** [comment] 2022-08-23 19:38
Hmm… Actually, the crabsnake eggs seem to have ‘spawned’ after scanning the crabsnake and hatching another one. This was not required for the Mesmer egg. I wonder what the exact requirements are?

**Comment by tinyhoot** [comment] 2022-08-26 09:42
This is a bug I've been aware of for some time, and unfortunately this is vanilla behaviour. Sometimes (often) existing unidentified eggs in the world are not updated when you hatch one. However, from my testing, any eggs spawned from that point on are their proper identified variants.

Allowing unidentified eggs in recipes is something I looked into, but it's not quite as simple as it looks, since the game actually considers the unidentified and identified eggs as two completely separate items, repeated for _every possible egg in the game._ Allowing recipes to use the unidentified variant would be like allowing every recipe that uses titanium to use copper instead. It would mean registering a whole second recipe, for each possible combination of ingredients. For recipes that happen to require multiple eggs, all the possible combinations would quickly clutter up your PDA for little gain.

It might be possible to write a patch that fixes the vanilla bug altogether by actively searching for undiscovered eggs in the world and inventory, and replacing them on the fly with their discovered counterparts if necessary. It is my understanding that this is more or less how the game already handles the "discovery" process, but for some reason it seems to fail every so often.

As for the eggs themselves not spawning, I've never looked into the specifics of the reproduction mechanics, but I do know that there is a timer that varies by species, with the bigger fauna subject to the longest timers. It wouldn't surprise me if crabsnakes made the top of that list. Either way the randomiser does not interfere with vanilla behaviour here.

**Comment by jet082** [comment] 2022-08-26 11:45
I see, interesting. I can see two possible paths then.

1) Identified Egg Recipes. Which is to say, a recipe for a "Crabsnake Egg" that requires simply an "unidentified Crabsnake Egg." Using your fabricator as an egg identifier, basically. Then you could use the eggs as normal.
2) Waiting for Subnautica 2.0 to drop and hoping it fixes things (and doesn't break mod libraries too badly)

**Comment by tinyhoot** [comment] 2022-08-26 13:50
The egg recipes are an interesting idea, but I don't see how they'd work in practice without completely circumventing the need for an alien containment, since all you'd need is the fabricator. It's also tricky to add these recipes to the fabricator as soon as you hatch the first egg from that species, since the craft tree gets built only when you first interact with a fabricator, and then persists for as long as the game is running (even across save games). You could potentially add the recipes as undiscovered/inactive and unlock them on hatching, but I'd have to dig into the specifics.

I do think the idea of having discovered eggs more readily available has merit. Perhaps as a separate config option that makes all eggs discovered from the start?

Waiting for Subnautica 2.0 is a possibility and it is known that it'll include some bugfixes, but we've been waiting for it to drop for a long while now. Based on UWE's latest blog post, I'm not convinced it'll even be out this year. Relying on a possible fix in a far off future seems a bit shaky to me. The point about not breaking libraries too badly is also moot, since the backport of BZ content alone will break a lot of mods, including this one.

**Comment by tinyhoot** [comment] 2023-01-04 10:22
From my testing, this bug was thankfully fixed in Subnautica 2.0.

**Closed by tinyhoot** 2023-01-04 10:22 UTC
Labels: bug
